services:
  app:
    build:
      context: .
    env_file: .env
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - redis
      - db
    networks:
      - app-network

  redis:
    image: 'redis:7-alpine'
    networks:
      - app-network

  db:
    image: 'postgres:17-alpine'
    env_file: .env
    ports:
      - '3002:5432'
    volumes:
      - chat-db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chat-db:
